describe("initial", function()
  it("should work", function()
    assert.is_equal(1 + 1, 2)
  end)
  it("should't work", function()
    assert.is_equal(1 + 1, 1)
  end)
end)
describe("initial2", function()
  it("should work", function()
    assert.is_equal(1 + 1, 2)
  end)
end)
